# Generated by Django 2.0.7 on 2018-07-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.IntegerField(primary_key=True, serialize=False)),
                ('word_text', models.CharField(max_length=64)),
                ('illustration', models.ImageField(height_field=256, upload_to='', width_field=256)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('forget_count', models.IntegerField()),
            ],
        ),
    ]
