# Generated by Django 2.0.7 on 2018-07-11 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='illustration',
        ),
        migrations.AddField(
            model_name='word',
            name='word_image_id',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='forget_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wordcards.Word'),
        ),
    ]
