# Generated by Django 2.0.7 on 2018-07-11 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordcards', '0002_auto_20180711_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_def',
            field=models.CharField(default='A kind of bird with black feather. It is considerted to possess high intelligence.', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordcards.Word'),
        ),
    ]
