# Generated by Django 2.0.7 on 2018-07-11 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wordcards', '0003_auto_20180711_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='../media/image'),
            preserve_default=False,
        ),
    ]
