# Generated by Django 2.0.7 on 2018-07-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcards', '0005_auto_20180711_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='correct_in_row',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
